# Python CircleCI 2.0 configuration file
# Updating CircleCI configuration from v1 to v2
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Test image build
          command: |
            docker build -t jupyterhub/jupyterhub .
            docker build -t jupyterhub/jupyterhub-onbuild:${CIRCLE_TAG:-latest} onbuild

  deploy:
    machine: true
    branches:
      only: master
    tags:
      only: /.*/
    steps:
      - run:
          name: Push master branch to main image
          command: |
            docker images
            docker login -u $DOCKER_USER -p $DOCKER_PASS -e unused@example.com
            docker push jupyterhub/jupyterhub-onbuild:${CIRCLE_TAG:-latest}

ignore_workflows:
  version: 2
  build-and-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
